version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./www:/www
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx-error.log:/var/log/nginx/error.log
            - ./logs/nginx-access.log:/var/log/nginx/access.log
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./www:/www
        networks:
            - code-network
    mysql:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: adminroot
            MYSQL_USER: fajar
            MYSQL_PASSWORD: admin
        networks:
            - code-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - 8090:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        networks:
            - code-network
networks:
    code-network:
        driver: bridge